# Generated by Django 6.0.1 on 2026-01-07 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexSelect', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('location', models.CharField(default='Москва', max_length=200, verbose_name='Локация')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('benefits', models.TextField(blank=True, verbose_name='Условия и бонусы')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(default='руб.', max_length=10, verbose_name='Валюта')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('remote', 'Удаленная работа'), ('freelance', 'Фриланс'), ('internship', 'Стажировка')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('experience', models.CharField(choices=[('no_experience', 'Без опыта'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='no_experience', max_length=20, verbose_name='Требуемый опыт')),
                ('technologies', models.CharField(blank=True, help_text='Укажите технологии через запятую', max_length=500, verbose_name='Технологии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('closed', 'Закрыта'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Удаленная работа')),
                ('is_relocation', models.BooleanField(default=False, verbose_name='Релокация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
