# Generated by Django 6.0.1 on 2026-01-08 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexSelect', '0004_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='response_count',
            field=models.IntegerField(default=0, verbose_name='Количество откликов'),
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Расскажите, почему вы подходите для этой вакансии', max_length=2000, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('viewed', 'Просмотрено'), ('invited', 'Приглашение на собеседование'), ('rejected', 'Отказ'), ('accepted', 'Принято')], default='pending', max_length=20, verbose_name='Статус отклика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_notes', models.TextField(blank=True, help_text='Внутренние заметки по отклику', verbose_name='Заметки администратора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='apexSelect.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created_at'],
                'unique_together': {('vacancy', 'user')},
            },
        ),
    ]
