# Generated by Django 6.0.1 on 2026-01-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexSelect', '0005_vacancy_response_count_vacancyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponse',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата собеседования'),
        ),
        migrations.AddField(
            model_name='vacancyresponse',
            name='recruiter_notes',
            field=models.TextField(blank=True, help_text='Внутренние заметки по кандидату', verbose_name='Заметки рекрутера'),
        ),
        migrations.AddField(
            model_name='vacancyresponse',
            name='recruiter_status',
            field=models.CharField(choices=[('new', 'Новый'), ('screening', 'Скрининг'), ('interview', 'Интервью'), ('technical', 'Техническое собеседование'), ('offer', 'Оффер'), ('hired', 'Принят'), ('rejected', 'Отказ'), ('no_response', 'Нет ответа')], default='new', help_text='Статус кандидата в процессе найма', max_length=20, verbose_name='Статус рекрутера'),
        ),
        migrations.AddField(
            model_name='vacancyresponse',
            name='salary_offer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предложенная зарплата'),
        ),
    ]
